// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXOhK9Rr9GC-BaryCRMUpW6g8q8hUdE90',
    appId: '1:204736832402:web:09e21a43c94b93ba7f574b',
    messagingSenderId: '204736832402',
    projectId: 'chat-app-2e7fc',
    authDomain: 'chat-app-2e7fc.firebaseapp.com',
    storageBucket: 'chat-app-2e7fc.firebasestorage.app',
    measurementId: 'G-7PZE5807RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqwO7QFWMZ7dXHtWOdeuFD9EDd_W1yyUg',
    appId: '1:204736832402:android:18e387911bf8f0aa7f574b',
    messagingSenderId: '204736832402',
    projectId: 'chat-app-2e7fc',
    storageBucket: 'chat-app-2e7fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGA_gQK_WNVpY8Vrsj_tnV0mBJftzlbG4',
    appId: '1:204736832402:ios:14871118a6ec17887f574b',
    messagingSenderId: '204736832402',
    projectId: 'chat-app-2e7fc',
    storageBucket: 'chat-app-2e7fc.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGA_gQK_WNVpY8Vrsj_tnV0mBJftzlbG4',
    appId: '1:204736832402:ios:14871118a6ec17887f574b',
    messagingSenderId: '204736832402',
    projectId: 'chat-app-2e7fc',
    storageBucket: 'chat-app-2e7fc.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXOhK9Rr9GC-BaryCRMUpW6g8q8hUdE90',
    appId: '1:204736832402:web:e2a1ba335159295e7f574b',
    messagingSenderId: '204736832402',
    projectId: 'chat-app-2e7fc',
    authDomain: 'chat-app-2e7fc.firebaseapp.com',
    storageBucket: 'chat-app-2e7fc.firebasestorage.app',
    measurementId: 'G-4K3NW755WM',
  );
}
